/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TrackPanel.java
 *
 * Created on Dec 30, 2010, 3:13:49 PM
 */

package wiicamblobtrack;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


/**
 *
 * @author mes
 */
public class TrackPanel extends javax.swing.JPanel {

    private Blob[] b;

    /** Creates new form TrackPanel */
    public TrackPanel() {
        initComponents();
        setFocusable(true);
        setBackground(Color.WHITE);
        setDoubleBuffered(true);

        b = new Blob[4];

        for (int i=0; i < 4; i++) {
            b[i] = new Blob(i*20+5, i*20+5);
            b[i].setVisible(true);
        }
        
    }

    public Blob[] getBlobs() {
        return b;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        Graphics2D g2d = (Graphics2D) g;

        for (int i=0; i < 4; i++) {
            if (b[i].isVisible())
                g2d.drawImage(b[i].getImage(), b[i].getX()-12, b[i].getY()-12, this);
                // TODO: encapsulate x, y & image size in Blob
        }
        
        Toolkit.getDefaultToolkit().sync();
        g.dispose();
    }

    public void actionPerformed(ActionEvent e) {
//        craft.move();
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
